### PR TITLE
#159965277 Enable a user to view notifications 

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
#### What does this PR do?
- enables a user to view all notifications they have received.

#### Description of tasks to be completed
- display a badge showing number of notifications a user has
- display all notifications for a given user when the above badge is clicked
- enable users to mark a notification or all notifications as read
- enable users to delete notifications
- have tests for the feature

#### How should this be manually tested
$ git clone https://github.com/andela/mag-ah-frontend.git
$ git checkout ft-view-notifications-159965277
$ cd mag-ah-frontend
$ copy .env_sample to .env
$ npm install
$ npm start
- Navigate to http://localhost:3000
- Locate a *badge* on the *navigation bar next to user profile icon* showing the number of notifications you have.
- Click the badge which will open a drop-down menu listing all your notifications.
- Experiment with the options provided against each notification item.

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[User should be able to view notifications](https://www.pivotaltracker.com/story/show/159965277)

#### Screenshots (if appropriate)
image

image

### CODE REVIEW

**Comment by pabishai** [comment]
@meshack-mbuvi I like the UI though the first screenshot and the last are not the same

**Comment by meshack-mbuvi** [comment]
@PAbishai I think you were viewing something different.

**Comment by pabishai** [comment]
@meshack-mbuvi I suggest the font style of the Mark as read and the actual notification to match. The green is too bright

**Comment by pngg** [comment]
> @meshack-mbuvi I suggest the font style of the Mark as read and the actual notification to match. The green is too bright

@meshack-mbuvi I second @PAbishai on this, could we make the font for `Mark all as read` smaller and greyed out?

**Comment by pabishai** [comment]
That looks OK to me.

**Pull request merged**
